### ISSUE TITLE
cycle through all clouds

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/CommunityClouds#48]
I can't believe I'm about to make a feature request, but. . . .

I periodically check the site and just want to cycle through all the clouds, I wonder if a "next cloud" or something like that option would be useful / helpful?

Note I'm only asking because there are SO MANY clouds!

**Comment by Gothor** [comment]
The same here. I was thinking about adding a navigation through up and down keys.

**Comment by JonathanHHenson** [comment]
Working on it :)

**Comment by JonathanHHenson** [comment]
https://github.com/CodingTrain/CommunityClouds/pull/49
